"""empty message

Revision ID: 67e38c66f078
Revises: e84c82d1cc6a
Create Date: 2023-06-11 15:13:37.896964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e38c66f078'
down_revision = 'e84c82d1cc6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('completed_content_blocks_student_id_fkey', 'completed_content_blocks', type_='foreignkey')
    op.drop_constraint('completed_content_blocks_content_block_id_fkey', 'completed_content_blocks', type_='foreignkey')
    op.create_foreign_key(None, 'completed_content_blocks', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'completed_content_blocks', 'blocks', ['content_block_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completed_content_blocks', type_='foreignkey')
    op.drop_constraint(None, 'completed_content_blocks', type_='foreignkey')
    op.create_foreign_key('completed_content_blocks_content_block_id_fkey', 'completed_content_blocks', 'blocks', ['content_block_id'], ['id'])
    op.create_foreign_key('completed_content_blocks_student_id_fkey', 'completed_content_blocks', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###
