"""student_id_block_id_unique

Revision ID: e0a2cbfd7d6c
Revises: 67e38c66f078
Create Date: 2023-06-12 11:45:56.274131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a2cbfd7d6c'
down_revision = '67e38c66f078'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('student_block_association', 'completed_content_blocks', ['student_id', 'content_block_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_block_association', 'completed_content_blocks', type_='unique')
    # ### end Alembic commands ###
